### ISSUE TITLE
docker-compose.yml has invalid config and failing to start the services

### ISSUE THREAD

**Issue by woss** [textileio/go-buckets#5]
When using this docker-compose file https://github.com/textileio/go-buckets/blob/master/cmd/buckd/docker-compose.yml services are failing: 

Service `buckets` is failing with the ;
```sh
buckets_1  | 2021-05-13T12:36:44.052Z   DEBUG   buckd   buckd/main.go:248       loaded config: {
buckets_1  |   "addr": {
buckets_1  |     "api": "0.0.0.0:5000",
buckets_1  |     "api_proxy": "0.0.0.0:5050",
buckets_1  |     "ipfs": {
buckets_1  |       "api": "/ip4/127.0.0.1/tcp/5001"
buckets_1  |     },
buckets_1  |     "mongo_name": "buckets",
buckets_1  |     "mongo_uri": "mongodb://127.0.0.1:27017",
buckets_1  |     "powergate": {
buckets_1  |       "api": ""
buckets_1  |     },
buckets_1  |     "threads": {
buckets_1  |       "host": "/ip4/0.0.0.0/tcp/4006",
buckets_1  |       "mongo_name": "",
buckets_1  |       "mongo_uri": ""
buckets_1  |     }
buckets_1  |   },
buckets_1  |   "dns": {
buckets_1  |     "domain": "",
buckets_1  |     "token": "",
buckets_1  |     "zone_id": ""
buckets_1  |   },
buckets_1  |   "gateway": {
buckets_1  |     "subdomains": false
buckets_1  |   },
buckets_1  |   "ipns": {
buckets_1  |     "republish_concurrency": 100,
buckets_1  |     "republish_schedule": "0 1 * * *"
buckets_1  |   },
buckets_1  |   "log": {
buckets_1  |     "debug": "true",
buckets_1  |     "file": ""
buckets_1  |   },
buckets_1  |   "repo": "/data/buckets"
buckets_1  | }
buckets_1  | > Error! Failed to parse multiaddr "0.0.0.0:5050": must begin with /

```

then when I change the parts that are failing like this:
```
      - BUCK_ADDR_API=/ip4/0.0.0.0/tcp/5000
      - BUCK_ADDR_API_PROXY=/ip4/0.0.0.0/tcp/5050
```
the service fails again, with the different error:

```sh
buckets_1  | 2021-05-13T12:37:06.910Z   DEBUG   buckd   buckd/main.go:248       loaded config: {
buckets_1  |   "addr": {
buckets_1  |     "api": "/ip4/0.0.0.0/tcp/5000",
buckets_1  |     "api_proxy": "/ip4/0.0.0.0/tcp/5050",
buckets_1  |     "ipfs": {
buckets_1  |       "api": "/ip4/127.0.0.1/tcp/5001"
buckets_1  |     },
buckets_1  |     "mongo_name": "buckets",
buckets_1  |     "mongo_uri": "mongodb://127.0.0.1:27017",
buckets_1  |     "powergate": {
buckets_1  |       "api": ""
buckets_1  |     },
buckets_1  |     "threads": {
buckets_1  |       "host": "/ip4/0.0.0.0/tcp/4006",
buckets_1  |       "mongo_name": "",
buckets_1  |       "mongo_uri": ""
buckets_1  |     }
buckets_1  |   },
buckets_1  |   "dns": {
buckets_1  |     "domain": "",
buckets_1  |     "token": "",
buckets_1  |     "zone_id": ""
buckets_1  |   },
buckets_1  |   "gateway": {
buckets_1  |     "subdomains": false
buckets_1  |   },
buckets_1  |   "ipns": {
buckets_1  |     "republish_concurrency": 100,
buckets_1  |     "republish_schedule": "0 1 * * *"
buckets_1  |   },
buckets_1  |   "log": {
buckets_1  |     "debug": "true",
buckets_1  |     "file": ""
buckets_1  |   },
buckets_1  |   "repo": "/data/buckets"
buckets_1  | }
buckets_1  | > Error! Failed to parse multiaddr "": empty multiaddr
````

Service `threads` fails with the :
```sh
❯ docker-compose -f docker-compose-textile.yml up threads
Recreating test_ipfs_threads_1 ... done
Attaching to test_ipfs_threads_1
threads_1  | panic: runtime error: invalid memory address or nil pointer dereference
threads_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x134775b]
threads_1  |
threads_1  | goroutine 1 [running]:
threads_1  | main.main()
threads_1  |    /go-threads/cmd/threadsd/main.go:129 +0x135b
```

Also I'm seeing that this dockerfile does not include the mongodb, should it?

**Comment by sanderpick** [comment]
Hey @woss, thanks for the issue. The published buckets image is out of date. I can push a new image tomorrow. We haven't officially migrated yet to this repo from https://github.com/textileio/textile, hence the poorly maintained docker images. That said, this is the one you want if you're interested in avoiding mongodb and the hub.

**Comment by sanderpick** [comment]
Hey @woss, I've updated the docker compose files on this [Bucking Pinning branch](https://github.com/textileio/go-buckets/tree/sander/bps) that will be merged soon.

From that branch you can run the compose file, which builds the `buckets` image and uses the correct `threads` image:

```
env REPO_PATH=~/.buckets docker-compose -f cmd/buckd/docker-compose.yml up
```

Then build and install `buck`:
```
make install-buck
```

With `buck` you can init a bucket in a local folder as per the README:

```
buck init
```

Using `cmd/buckd/docker-compose-dev.yml` will build `buckets` locally:

```
env REPO_PATH=~/.buckets make buck-up
```

**Comment by woss** [comment]
Thanks @sanderpick. I'll give it a go and report back. Let's keep this open until I verify it works. 

Just a question related to the handling the storage (volumes). Wouldn't it be better to have the `REPO_PATH` as a volume instead of the locally mounted volume? Since the images are built with `sudo` it creates the files owned by the `root`. Any specific reason why that's like that?

**Comment by sanderpick** [comment]
Nope, no good reason. I would take a PR to improve that. I can also take a look this evening / tomorrow.

**Comment by woss** [comment]
I don't mind making a PR for that kind of change :)

**Comment by sanderpick** [comment]
fyi @woss https://github.com/textileio/go-buckets/pull/2 has been merged.

**Comment by woss** [comment]
the services are up and running and it's possible to add/create and push to the bucket. one thing ( maybe not relevant but i'd like to cover it) is that the `buck links` doesn't list the static website link, only shows the threads and the ipns, if that's ok I'll proceed with the PR for the change of the volume. 

Minor thing, I believe, when I click on threads link it shows 404 as a json

**Comment by sanderpick** [comment]
Nice! 

`buck` links will show the WWW link if the daemon is started with `--gatewayWwwDomain=mydomain.com` or the correspoinding env var `GATEWAY_WWW_DOMAIN`.

Is the 404 expected and just not returning the right code+mime type or does the gateway look broken?

**Comment by woss** [comment]
I'm not sure is this expected but after I create a bucket, do the push and links, this is what i see when i open Thread link
![image](https://user-images.githubusercontent.com/80440/119227318-94c77280-bb0d-11eb-9fc3-f42f9f3b7325.png)

**Comment by woss** [comment]
@sanderpick fyi here is the PR https://github.com/textileio/go-buckets/pull/6
